In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [8]:
type(list_)

list

In [11]:
array_list.dtype

dtype('<U1')

## Both have different data type.

## Q2

In [12]:
[type(i) for i in list_]

[str, str, str, str, str]

In [13]:
[i.dtype for i in array_list]

[dtype('<U1'), dtype('<U1'), dtype('<U1'), dtype('<U1'), dtype('<U1')]

Q3

In [15]:
array_list = np.array(object = list_, dtype = int)

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
[i.dtype for i in array_list]

[dtype('int32'),
 dtype('int32'),
 dtype('int32'),
 dtype('int32'),
 dtype('int32')]

In [18]:
[type(i) for i in list_]

[str, str, str, str, str]

In [19]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

## Q5

In [26]:
arr = np.zeros((3,3))

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

## Q6

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])